In [ ]:
import torch
import numpy as np

In [ ]:
a = torch.tensor(np.arange(10))
b = torch.FloatTensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(a.shape, b.shape)

torch.Size([10]) torch.Size([10])


In [ ]:
print(a.dim(), b.dim())

1 1


In [ ]:
print(a.size(), b.size())

torch.Size([10]) torch.Size([10])


In [ ]:
print(a[:5])
print(a[3:])

tensor([0, 1, 2, 3, 4])
tensor([3, 4, 5, 6, 7, 8, 9])


In [ ]:
import torch

In [ ]:
a = torch.FloatTensor([[1, 1]])
b = torch.FloatTensor([[7, 7]])
print(a + b)

tensor([[8., 8.]])


In [ ]:
print(a.shape)
print(b.shape)

torch.Size([1, 2])
torch.Size([1, 2])


In [ ]:
a = torch.FloatTensor([[1, 7]])
b = torch.FloatTensor([5])
print(a + b)

tensor([[ 6., 12.]])


In [ ]:
a = torch.FloatTensor([[1, 7]])
b = torch.FloatTensor([[5], [6]])
print(a + b)

tensor([[ 6., 12.],
        [ 7., 13.]])


In [ ]:
print(a)

tensor([[1., 7.]])


In [ ]:
print(a.shape)

torch.Size([1, 2])


In [ ]:
print(b)

tensor([[5.],
        [6.]])


In [ ]:
print(b.shape)

torch.Size([2, 1])


In [ ]:
import torch

In [ ]:
a = torch.FloatTensor([[1, 2], [3, 4]])
b = torch.FloatTensor([[1], [2]])

In [ ]:
print(a.matmul(b))

tensor([[ 5.],
        [11.]])


In [ ]:
print(a * b)

tensor([[1., 2.],
        [6., 8.]])


In [ ]:
print(a.mul(b))

tensor([[1., 2.],
        [6., 8.]])


In [ ]:
import torch
import numpy as np

In [ ]:
a = np.arange(24).reshape(-1, 2, 4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [ ]:
print(a.shape)

(3, 2, 4)


In [ ]:
b = torch.FloatTensor(a)
print(b)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.]],

        [[ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]],

        [[16., 17., 18., 19.],
         [20., 21., 22., 23.]]])


In [ ]:
print(b.shape)

torch.Size([3, 2, 4])


In [ ]:
print(b.view([-1, 4]))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]])


In [16]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [17]:
class Model(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(3, 1)

  def forward(self, x):
    return self.linear(x)

In [18]:
x_data = torch.FloatTensor([[73, 80, 75],
                            [93, 88, 93],
                            [89, 91, 90],
                            [96, 98, 100],
                            [73, 66, 70]])

In [19]:
y_data = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [20]:
model = Model()

In [21]:
optimizer = optim.SGD(model.parameters(), lr=1e-5)

In [22]:
epoch = 30

for i in range(epoch):
  prediction = model(x_data)
  cost = F.mse_loss(prediction, y_data)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  print('Epoch {:4d}/{}, Cost : {:.6f}'.format(
      i, epoch, cost.item()
  ))

Epoch    0/30, Cost : 79519.835938
Epoch    1/30, Cost : 24925.503906
Epoch    2/30, Cost : 7813.074219
Epoch    3/30, Cost : 2449.237061
Epoch    4/30, Cost : 767.958374
Epoch    5/30, Cost : 240.966965
Epoch    6/30, Cost : 75.783417
Epoch    7/30, Cost : 24.006704
Epoch    8/30, Cost : 7.777595
Epoch    9/30, Cost : 2.690481
Epoch   10/30, Cost : 1.095932
Epoch   11/30, Cost : 0.596088
Epoch   12/30, Cost : 0.439362
Epoch   13/30, Cost : 0.390179
Epoch   14/30, Cost : 0.374724
Epoch   15/30, Cost : 0.369821
Epoch   16/30, Cost : 0.368248
Epoch   17/30, Cost : 0.367709
Epoch   18/30, Cost : 0.367479
Epoch   19/30, Cost : 0.367375
Epoch   20/30, Cost : 0.367294
Epoch   21/30, Cost : 0.367217
Epoch   22/30, Cost : 0.367146
Epoch   23/30, Cost : 0.367080
Epoch   24/30, Cost : 0.367005
Epoch   25/30, Cost : 0.366945
Epoch   26/30, Cost : 0.366877
Epoch   27/30, Cost : 0.366804
Epoch   28/30, Cost : 0.366742
Epoch   29/30, Cost : 0.366666
